name: nyxara
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  flutter_bloc:
  mongo_dart:
  bcrypt: 
  flutter_dotenv: 
  http: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
