name: nyxara
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  flutter_bloc:
  bcrypt: 
  flutter_dotenv: 
  http: ^1.4.0
  bloc: ^9.0.0
  meta: ^1.16.0
  flutter_3d_controller:
  o3d: ^3.1.3
  syncfusion_flutter_charts: ^29.2.7
  shared_preferences:
  emailjs: ^4.0.0
  fluttertoast:
dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
